## Here is an example for Makefiles.

syntax "makefile" "Makefile[^/]*$" "\.(make|mk)$"

#color red "[:=]"
#color green "[:=]"
color magenta "\<(if|ifeq|else|endif)\>"
color green "\$+[{(][a-zA-Z0-9_-]+[})]"
color blue "^[^ 	]+:"
#color green "#.*$"
color red "#.*$"

## Trailing whitespace.
color ,green "[[:space:]]+$"

##Srtings
color cyan ""(\\.|[^"])*"" "'(\\.|[^'])*'"
