## Here is an example for Makefiles.

syntax "makefile" "Makefile[^/]*$" "\.(make|mk)$"

#color red "[:=]"
color green "[:=]"
color magenta "\<(if|ifeq|else|endif)\>"
color blue "\$+[{(][a-zA-Z0-9_-]+[})]"
color brightblue "^[^ 	]+:"
#color green "#.*$"
color red "#.*$"

## Trailing whitespace.
color ,green "[[:space:]]+$"
